[*] Running ...
[*] Dataset loaded: E:\Projects\CO\reevo-main_1/problems/tsp_gls\dataset/train200_dataset.npy with 10 instances.
TypeError: only length-1 arrays can be converted to Python scalars

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\Projects\CO\reevo-main_1/problems/tsp_gls/eval.py", line 51, in <module>
    obj = solve(instance)
          ^^^^^^^^^^^^^^^
  File "E:\Projects\CO\reevo-main_1/problems/tsp_gls/eval.py", line 21, in solve
    heu = heuristics(inst.distmat.copy())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Projects\CO\reevo-main_1\problems\tsp_gls\gpt.py", line 23, in heuristics_v2
    
ValueError: setting an array element with a sequence.
