[*] Running ...
[*] Dataset loaded: E:\Projects\CO\reevo-main_1/problems/tsp_gls\dataset/train200_dataset.npy with 10 instances.
Traceback (most recent call last):
  File "E:\Projects\CO\reevo-main_1/problems/tsp_gls/eval.py", line 51, in <module>
    obj = solve(instance)
          ^^^^^^^^^^^^^^^
  File "E:\Projects\CO\reevo-main_1/problems/tsp_gls/eval.py", line 21, in solve
    heu = heuristics(inst.distmat.copy())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Projects\CO\reevo-main_1\problems\tsp_gls\gpt.py", line 9, in heuristics_v2
    heuristic_matrix = np.exp(np.abs(distance_matrix - np.min(distance_matrix, axis=0) - 
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda3\envs\reevo\Lib\site-packages\numpy\core\fromnumeric.py", line 2810, in max
    return _wrapreduction(a, np.maximum, 'max', axis, None, out,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda3\envs\reevo\Lib\site-packages\numpy\core\fromnumeric.py", line 88, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
numpy.exceptions.AxisError: axis 2 is out of bounds for array of dimension 2
