[*] Running ...
[*] Dataset loaded: E:\Projects\CO\reevo-main_1/problems/tsp_gls\dataset/train200_dataset.npy with 10 instances.
[*] Instance 0: 10.662099940546348
[*] Instance 1: 10.711281900321072
[*] Instance 2: 10.886366529439798
[*] Instance 3: 10.43645695473396
E:\Projects\CO\reevo-main_1\problems\tsp_gls\gpt.py:30: RuntimeWarning: invalid value encountered in log
[*] Instance 4: 10.684959789676864
[*] Instance 5: 10.392297741281627
[*] Instance 6: 11.222982803711096
[*] Instance 7: 10.743129036096533
[*] Instance 8: 10.606640182406887
[*] Instance 9: 10.28231136840656
[*] Average:
10.662852624662076
