[*] Running ...
[*] Dataset loaded: D:\ProgramLanguages\Programs\Python\code-gen\reevo/problems/tsp_gls\dataset/train200_dataset.npy with 10 instances.
D:\ProgramLanguages\Programs\Python\code-gen\reevo\problems\tsp_gls\gpt.py:20: RuntimeWarning: invalid value encountered in divide
  heuristic_matrix[i, j] = heuristic_value
Traceback (most recent call last):
  File "D:\ProgramLanguages\Programs\Python\code-gen\reevo/problems/tsp_gls/eval.py", line 51, in <module>
    obj = solve(instance)
          ^^^^^^^^^^^^^^^
  File "D:\ProgramLanguages\Programs\Python\code-gen\reevo/problems/tsp_gls/eval.py", line 22, in solve
    assert tuple(heu.shape) == (inst.n, inst.n)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
