[*] Running ...
[*] Dataset loaded: E:\Projects\CO\reevo-main_1/problems/tsp_gls\dataset/train200_dataset.npy with 10 instances.
Traceback (most recent call last):
  File "E:\Projects\CO\reevo-main_1/problems/tsp_gls/eval.py", line 51, in <module>
    obj = solve(instance)
          ^^^^^^^^^^^^^^^
  File "E:\Projects\CO\reevo-main_1/problems/tsp_gls/eval.py", line 21, in solve
    heu = heuristics(inst.distmat.copy())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Projects\CO\reevo-main_1\problems\tsp_gls\gpt.py", line 11, in heuristics_v2
    heuristic_matrix = 1.0 / distance_matrix
                                             
numpy.exceptions.AxisError: axis 1 is out of bounds for array of dimension 1
